sylius_grid:
    templates:
        action:
            updateQuarantine: "@MonsieurBizSyliusAntiSpamPlugin/Admin/Grid/Action/update_quarantine.html.twig"
    grids:
        sylius_admin_customer:
            fields:
                quarantine:
                    type: twig
                    label: monsieurbiz_anti_spam.ui.quarantine
                    path: quarantineItem
                    options:
                        template: '@MonsieurBizSyliusAntiSpamPlugin/Admin/Grid/Field/quarantine_item.html.twig'
            actions:
                subitem:
                    breaking_quarantine:
                        type: updateQuarantine
