sylius_twig_hooks:
    hooks:
        'sylius_shop.account.register.content.form':
            monsieurbiz_anti_spam_captcha:
                template: '@MonsieurBizSyliusAntiSpamPlugin/Shop/form_captcha.html.twig'
                priority: 0
        
        'sylius_shop.contact.contact_request.content.form':
            monsieurbiz_anti_spam_captcha:
                template: '@MonsieurBizSyliusAntiSpamPlugin/Shop/form_captcha.html.twig'
                priority: 0
