services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    MonsieurBiz\SyliusAntiSpamPlugin\:
        resource: '../../*'
        exclude: '../../{Entity,Migrations}'

    MonsieurBiz\SyliusAntiSpamPlugin\Form\Extension\:
        resource: '../../Form/Extension'
        tags: ['form.type_extension']
