parameters:
    monsieurbiz.anti_spam.quarantine_item.level_suspected: !php/const \MonsieurBiz\SyliusAntiSpamPlugin\Entity\QuarantineItemInterface::LEVEL_SUSPECTED
    monsieurbiz.anti_spam.quarantine_item.level_likely: !php/const \MonsieurBiz\SyliusAntiSpamPlugin\Entity\QuarantineItemInterface::LEVEL_LIKELY
    monsieurbiz.anti_spam.quarantine_item.level_proven: !php/const \MonsieurBiz\SyliusAntiSpamPlugin\Entity\QuarantineItemInterface::LEVEL_PROVEN
    monsieurbiz.anti_spam.recaptcha_validator.routes_to_check:
        - 'sylius_shop_register'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind :
            $karserRecaptcha3Enabled: '%karser_recaptcha3.enabled%'

    MonsieurBiz\SyliusAntiSpamPlugin\:
        resource: '../../*'
        exclude: '../../{Entity,Migrations}'

    monsieurbiz.anti_spam.validators.registry: '@MonsieurBiz\SyliusAntiSpamPlugin\Registry\ValidatorsRegistry'

    monsieurbiz.anti_spam.quarantineable.registry:
        class: Sylius\Component\Registry\ServiceRegistry
        arguments:
            $className: MonsieurBiz\SyliusAntiSpamPlugin\Entity\QuarantineItemAwareInterface
            $context: 'quarantineable'

    MonsieurBiz\SyliusAntiSpamPlugin\Email\Sender:
        decorates: 'sylius.email_sender'
        arguments: ['@MonsieurBiz\SyliusAntiSpamPlugin\Email\Sender.inner']

    MonsieurBiz\SyliusAntiSpamPlugin\EventListener\QuarantineItemAwareListener:
        tags:
            - name: 'doctrine.event_listener'
              event: 'prePersist'

    MonsieurBiz\SyliusAntiSpamPlugin\EventListener\QuarantineInitializeUpdateListener:
        tags:
            - { name: kernel.event_listener, event: monsieurbiz_anti_spam.quarantine_item.initialize_update }

    MonsieurBiz\SyliusAntiSpamPlugin\EventListener\OrderCompleteListener:
        tags:
            - { name: kernel.event_listener, event: sylius.order.post_complete, method: liftQuarantine }

    MonsieurBiz\SyliusAntiSpamPlugin\Remover\ExceededQuarantineItemsRemover:
        arguments:
            $quarantineableRegistry: '@monsieurbiz.anti_spam.quarantineable.registry'
            $expirationPeriodsByLevel: {
                '%monsieurbiz.anti_spam.quarantine_item.level_suspected%': '%monsieurbiz.anti_spam.quarantine_item_exceeded_period.suspected%',
                '%monsieurbiz.anti_spam.quarantine_item.level_likely%': '%monsieurbiz.anti_spam.quarantine_item_exceeded_period.likely%',
                '%monsieurbiz.anti_spam.quarantine_item.level_proven%': '%monsieurbiz.anti_spam.quarantine_item_exceeded_period.proven%',
            }

    MonsieurBiz\SyliusAntiSpamPlugin\Validator\ReCaptcha3Validator:
        arguments:
            $routesToCheck: '%monsieurbiz.anti_spam.recaptcha_validator.routes_to_check%'
            $captchaMinimumScore: '%karser_recaptcha3.score_threshold%'

    MonsieurBiz\SyliusAntiSpamPlugin\Grid\Filter\QuarantineFilter:
        tags:
            -   name: sylius.grid_filter
                type: quarantine
                form_type: MonsieurBiz\SyliusAntiSpamPlugin\Form\Type\Filter\QuarantineFilterType

